### ISSUE TITLE
Impossible to remap more buttons

### ISSUE THREAD

**Issue by hfc2x** [matthewjustice/neomap#1]
I know this is very early, so I don't expect this program to cover all use cases.

I just wanted to see if I could remap the buttons for Fatal Fury Special's GOG release, but I have an Xbox One Hori Fighting Commander pad. This has 6 face buttons (A, B, X, Y, RB, RT), so I wanted to remap the buttons the way I use it on MAME (A for A, X for B, Y for C and RB for D) but the program is only supports controllers that use A, B, X and Y face buttons.

**Comment by matthewjustice** [comment]
That would be a nice feature to have. However, mapping RT (or LT) would require a different approach from what neomap does. The DotEmu executable contains a jump table for the various [SDL_GameControllerButton](https://wiki.libsdl.org/SDL_GameControllerButton) presses. Neomap works by swapping around entries in this table. Unfortunately, the table doesn't contain an entry for RT, meaning, at least in the code that neomap modifies, the DotEmu executable doesn't handle handle trigger inputs. Which makes sense, given that triggers are a different type of input - [SDL_GameControllerAxis](https://wiki.libsdl.org/SDL_GameControllerAxis).  So, I don't see an way to implement RT support within the current design of neomap. Sorry!
